name       : burp
version    : 2.2.14
release    : 3
source     :
    - https://github.com/grke/burp/archive/2.2.14.tar.gz : 823770025d98d158b6f3ae1703e2cac968f552b146bec2ab9351e50ff7aee9ad
license    : AGPL-3.0
component  : system.utils
summary    : Burp is a network backup and restore program
description: |
    Burp is a network backup and restore program.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(uthash)
    - acl-devel
    - librsync-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    install -D -m 00644 $pkgfiles/burp.tmpfiles $installdir/%libdir%/tmpfiles.d/burp.conf
