name       : burp
version    : 2.3.28
release    : 5
source     :
    - https://github.com/grke/burp/archive/2.3.28.tar.gz : 53f6c85705ab62542c244e57832e17da00044fb2c4daecd5cd742524eefb1678
license    : AGPL-3.0
component  : system.utils
summary    : Burp is a network backup and restore program
description: |
    Burp is a network backup and restore program.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(uthash)
    - acl-devel
    - librsync-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    install -D -m 00644 $pkgfiles/burp.tmpfiles $installdir/%libdir%/tmpfiles.d/burp.conf
